name: Deploy to EC2

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: dev

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Node.js and npm
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script: |
            # Navigate to your project directory
            cd /home/ubuntu/Task

            # Pull the latest code from the master branch
            git pull origin master

            # Install dependencies
            npm install

            # Build the project
            npm run build

            # Check if the application is already running
            if pm2 list | grep nest-hello-world; then
              pm2 restart nest-hello-world
            else
              pm2 start dist/main.js --name nest-hello-world
            fi

            # Save the PM2 process list and corresponding environments
            pm2 save
