name: CI/CD Pipeline

on:
  push:
    branches:
      - master
      
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm run test

      - name: Debug Environment Variables
        run: |
          echo "EC2_PUBLIC_DNS=${{ secrets.EC2_PUBLIC_DNS }}"
          echo "SSH_PRIVATE_KEY length: ${#secrets.SSH_PRIVATE_KEY}"

      - name: Add SSH key
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > private_key.pem
          chmod 600 private_key.pem
          ssh-keyscan -H ${{ secrets.EC2_PUBLIC_DNS }} >> ~/.ssh/known_hosts

      - name: Deploy to EC2
        run: |
          ssh -tt -i private_key.pem -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_PUBLIC_DNS }} << 'EOF'
            cd ~/nest/samples/01-cats-app
            git pull origin master
            npm install
            npm run build
            pm2 restart all || pm2 start dist/main.js --name nestjs-app
          EOF
        env:
          EC2_PUBLIC_DNS: ${{ secrets.EC2_PUBLIC_DNS }}
