name: AWS CLI Configuration

on:
  push:
    branches:
      - master  # Replace with your branch name
  pull_request:
    branches:
      - master  # Replace with your branch name

jobs:
  configure-aws-cli:
    runs-on: ubuntu-latest  # Use the appropriate GitHub Actions runner
   steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: "us-east-1"
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
